# config.yml

backend:
#  name: git-gateway
#  accept_roles: #optional - accepts all users if left out
#    - admin
#    - editor
  name: github
  repo: vosaul/Selim-RA
 # Path to your GitHub repository
media_folder: "/images/"
public_folder: "/images/"
publish_mode: editorial_workflow
collections:
- name: "posts"
  label: "Posts"
  create: true
  fields:
    - { label: 'Layout', name: 'layout', widget: 'string', default: 'post' }
    - { label: 'slug', name: 'slug', widget: 'string', required: false }
    - { label: 'image', name: 'image', widget: 'string', required: false}
    - { label: 'description', name: 'description', widget: 'string', required: false}
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
    - { label: "Author", name: "author", widget: "string", required: false}
    - { label: 'categories', name: 'categories', widget: 'string', required: false}
    - { label: 'tags', name: 'tags', widget: 'string', required: false}
    - { label: 'Body', name: 'body', widget: 'markdown' }
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  folder: "/_posts"

- name: "home"
  label: "Home"
  files:
    - name: home
      label: Home page data
      file: _data/home.yml
      fields:
      - label: 'support box'
        name: 'support_box'
        widget: 'object'
        required: false
        fields:
          - label: Title
            name: title
            widget: string 
          - label: subtitle
            name: subtitle
            widget: string
            required: false
          - label: text
            name: text
            widget: text
#            fields:
#              - name: "txt"
#                widget: text
          - label: image
            name: image
            widget: string 
           
      - label: third_box
        name: third_box
        widget: list
        fields:
        - name: txt
          widget: text

      - label: service_box
        name: service_box
        widget: object
        fields:
        - name: text
          label: text
          widget: list
          fields:
          - name: txt
            label: txt
            widget: text
        - name: services
          label: services
          widget: list
          fields: 
            - name: service
              widget: object
              fields:
              - name: title
                label: title
                widget: string
              - name: image
                label: image
                widget: string

      - label: sup_box
        name: sup_box
        widget: object
        fields:
          - label: Title
            name: title
            widget: string 
          - label: text
            name: text
            widget: text
            required: false
          - label: image
            name: image
            widget: string

      - label: webinar
        name: webinar
        widget: object
        fields:
          - label: Title
            name: title
            widget: string 
          - label: text
            name: text
            widget: text
            required: false
          - label: image
            name: image
            widget: string

      - label: crwn_box
        name: crwn_box
        widget: object
        fields:
          - label: text
            name: text
            widget: text
            required: false
          - label: image
            name: image
            widget: string

