# config.yml

backend:
#  name: git-gateway
#  accept_roles: #optional - accepts all users if left out
#    - admin
#    - editor
  name: github
  repo: vosaul/Selim-RA
 # Path to your GitHub repository
media_folder: "/images/"
public_folder: "/images/"
publish_mode: editorial_workflow
collections:

- name: "home"
  label: "Home"
  files:
    - name: home
      label: Home page data
      file: _data/home.yml
      fields:
      - label: 'support box'
        name: 'support_box'
        widget: 'object'
        required: false
        fields:
          - label: Title
            name: title
            widget: string 
          - label: subtitle
            name: subtitle
            widget: string
            required: false
#          - label: text
#            name: text
#            widget: list
#            add_to_top: true
#            minimize_collapsed: true
#            field:
#              - name: "text"
#                label: "text"
#                widget: text
          - { label: 'text', name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: tag, label: Tag, widget: string}  }

          - label: image
            name: image
            widget: string 
           
#      - label: third_box
#        name: third_box
#        widget: list
#        fields:
#        - name: txt
#          widget: text
      - { label: 'third_box', name: 'third_box', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: part, label: part, widget: text}  }

      - label: service_box
        name: service_box
        widget: object
        fields:
#        - name: text
#          label: text
#          widget: list
#          fields:
#          - name: txt
#            label: txt
#            widget: text
        - { label: 'text', name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: tag, label: Tag, widget: string}  }

        - name: services
          label: services
          widget: list
          fields: 
            - name: service
              label: service
              widget: object
              fields:
              - name: title
                label: title
                widget: string
              - name: image
                label: image
                widget: string

      - label: four_box
        name: four_box
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string 
          - label: text
            name: text
            widget: text
            required: false

      - label: sup_box
        name: sup_box
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string 
          - label: text
            name: text
            widget: text
            required: false
          - label: image
            name: image
            widget: string

      - label: webinar
        name: webinar
        widget: object
        fields:
          - label: Title
            name: title
            widget: string 
          - label: text
            name: text
            widget: text
            required: false
          - label: image
            name: image
            widget: string

      - label: crwn_box
        name: crwn_box
        widget: object
        fields:
#          - label: text
#            name: text
#            widget: text
#            required: false
#          - label: image
#            name: image
#            widget: string
          - { label: 'text', name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: paragraph, label: paragraph, widget: text}  }
          - { label: 'image', name: 'image', widget: 'string', required: false }


