# config.yml

backend:
  name: git-gateway
  accept_roles: 
    - admin
    - editor
#  name: github
  repo: selimerunkut/real_asset_support_website
  branch: main
 # Path to your GitHub repository
media_folder: "/images/"
public_folder: "/images/"
publish_mode: editorial_workflow
collections:

- name: "home"
  label: "home"
  files:
    - name: home
      label: Home page data
      file: "_data/home.yml"
      fields:
      - name: 'support_box'
        widget: 'object'
        required: false
        fields:
        - name: title
          widget: string 
        - name: subtitle
          widget: text
          required: false
        - { name: 'text', add_to_top: true, widget: 'list', required: false, field: {name: part, widget: text} }

        - name: image
          widget: string 
          required: false

      - { name: 'third_box', add_to_top: true, minimize_collapsed: true, widget: 'list', required: false, field: {name: part,  widget: text} }

      - name: service_box
        widget: object
        required: false
        fields:
        - { name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: part, widget: text} }

        - name: services
          widget: list
          required: false
          fields: 
          - name: title
            widget: string
            minimize_collapsed: true
          - name: image
            widget: string
            minimize_collapsed: true

      - name: four_box
        widget: object
        required: false
        fields:
        - name: title
          widget: string 
        - name: text
          widget: text
          required: false

      - name: sup_box
        widget: object
        required: false
        fields:
        - name: title
          widget: string 
        - name: text
          widget: text
          required: false
        - name: image
          widget: string

      - name: webinar
        widget: object
        required: false
        fields:
        - name: title
          widget: string 
        - name: image
          widget: string
        - { name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: part, widget: text} }

      - label: crwn_box
        name: crwn_box
        widget: object
        required: false
        fields:
        - { name: 'text', add_to_top: true, minimize_collapsed: true, widget: 'list', field: {name: part,  widget: text} }
        - { label: 'image', name: 'image', widget: 'string', required: false }

    - name: "impressum"
      label: "Impressum page data"
      file: "_data/impressum.yml"
      fields:
      - name: "title"
        widget: "string"
      - name: "contacts"
        widget: "text"
      - name: "blocks"
        widget: "list"
        allow_add: true
        fields:
        - name: "subtitle"
          widget: "string"
        - name: "text"
          widget: "text"

- name: "pages"
  label: pages
  folder: "/"
  fields:
  - name: layout
    widget: string
  - name: title
    widget: string
  - name: description
    widget: text
    required: false
  - name: image
    widget: string
    required: false
  - name: "author"
    widget: string
    required: false
  - name: "body"
    widget: "markdown"